name: Deploy to Apache Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Host Key
        run: |
          ssh-keyscan -H 20.116.219.63 >> ~/.ssh/known_hosts

      - name: Deploy Files
        run: |
          scp -r * azureuser@20.116.219.63:/var/www/html/

