name: Deploy to Apache Server

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up SSH and add private key from GitHub secrets
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Add the server to known hosts to avoid SSH prompt
      - name: Add Server to Known Hosts
        run: |
          ssh-keyscan -H 20.151.233.26 >> ~/.ssh/known_hosts  # Replace with your server's IP address

      # Step 4: Delete the previous files in Apache's web directory
      - name: Delete Previous Files
        run: |
          ssh hashmiirfan.ihq@hotmail.com@20.151.233.26 "sudo rm -rf /var/www/html/*"  # Use sudo if necessary

      # Step 5: Deploy the new files using SCP
      - name: Deploy Files to Server
        run: |
          scp -r * hashmiirfan.ihq@hotmail.com@20.151.233.26:/var/www/html/  # Replace with your username and server IP
